### ISSUE TITLE
Build errors

### ISSUE THREAD

**Issue by jeantimex** [wesleydotyang/HeifAndWebP#1]
After `pod install` and build, I receive the following errors:

<img width="271" alt="screen shot 2018-03-11 at 10 13 18 pm" src="https://user-images.githubusercontent.com/565300/37267153-b541015a-257b-11e8-88dc-82eb860b2db6.png">

What should I do? Thanks!

**Comment by wesleydotyang** [comment]
YYImage has errors while using pod. You could import YYImage manually before YYImage fix this issue.
